config/routes.rb
Rails.application.routes.draw do
 	devise_for :users
  

  root 'vooting_dashboard#index'

  get '/vooting_dashboard/:id' => 'vooting_dashboard#show', :as => 'vooting_dashboard'

  namespace :admin, module: nil  do
    root "admin#index"
    resources :users
    resources :vote_polls
  end
 	
 	resources :vote_options
 	resources :answers
 	resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/vooting_dashboard_controller.rb
class VootingDashboardController < ApplicationController
	def index
		# @vooting_all = VotePoll.all.where("startdate > ?",  DateTime.now)
		# today = DateTime.now
		# @vooting_all = VotePoll.all.where("today >= startdate AND today <= enddate")


		@vooting_all = VotePoll.all.where("startdate <= ? AND enddate >= ?", Date.today, Date.today )
	end

	

	def show
    @vote_poll = VotePoll.find(params[:id])
    @vote_option = @vote_poll.vote_options
	end

end

app/helpers/vooting_dashboard_helper.rb
module VootingDashboardHelper
end

app/views/vooting_dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Vote Polls</h1>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Startdate</th>
        <th>Enddate</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>

      <% @vooting_all.each do |vote_poll| %>
        <tr>
          <td><%= vote_poll.title %></td>
          <td><%= vote_poll.description %></td>
          <td><%= vote_poll.startdate.strftime "%a, %-d %b %Y " %></td>
          <td><%= vote_poll.enddate.strftime "%a, %-d %b %Y " %></td>
          <td><%= link_to 'Poll Detail', vooting_dashboard_path(vote_poll), :class=> 'btn btn-primary' %></td>
          <%# if current_user.present? %>
            <!-- <td><%#= link_to 'Poll Detail', vooting_dashboard_path(vote_poll), :class=> 'btn btn-primary' %></td> -->
          <%# else %>
          <!-- <td> -->
              <%#= link_to "Sign up", new_user_registration_path, :class=> 'btn btn-primary' %> 
              <!-- <%#= link_to "Login", new_user_session_path, :class=> 'btn btn-primary' %>&nbsp;  <h4>Please must log in </h4> -->
          <!-- </td> -->
          <%# end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/vooting_dashboard/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vote_poll.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vote_poll.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @vote_poll.startdate.strftime "%a, %-d %b %Y " %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @vote_poll.enddate.strftime "%a, %-d %b %Y" %>
  <%#= @vote_poll.enddate.strftime "%a, %-d %b %Y %I:%M %p" %>
</p>

<!-- Voting Answer form  -->
<%# byebug %>
<% if user_signed_in? %>
  <% if Answer.where(user_id: current_user.id, vote_poll_id: @vote_poll.id).first.present?  %><br>
    <span class="card-title"><h4>You have already upvoted !</h4></span>
  <% else %>
    <% if @vote_option.present? %>
      <%= form_for :answers, :url => answers_path  do |f| %>
        <%= f.hidden_field :vote_poll_id, :value => @vote_poll.id %>
          <% if current_user.present? %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
          <% end %>
          <% @vote_option.each do |option| %>
            <label class="radio-inline"><input type="radio" name="option_answer"  value= "<%= option.id %>"><%= option.title %></label>
          <% end %><br><br>
          <button type="submit">Submit</button>
      <% end %>
    <% end %>
  <% end %>   
<% else %>

  <%# cookies[:vote_poll_id] = @vote_poll.id %>
  <% if cookies[:vote_poll_id] && cookies[:vote_poll_id] == @vote_poll.id.to_s %><br>
    <span class="card-title"><h4>You have already upvoted !</h4></span>
  <% else %>  
    <% if @vote_option.present? %>
      <%= form_for :answers, :url => answers_path  do |f| %>
        <%= f.hidden_field :vote_poll_id, :value => @vote_poll.id %>
        <% if current_user.present? %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
        <% end %>
        <% @vote_option.each do |option| %>
          <label class="radio-inline"><input type="radio" name="option_answer"  value= "<%= option.id %>"><%= option.title %></label>
        <% end %><br><br>
        <button type="submit">Submit</button>
      <% end %>
    <% end %>
  <% end %>
<% end %>      

<!-- Percentage Details -->
<%# byebug %>
<% @vote_option.each do |op|%> 
  <% op_count = op.answers.count %> 
  <%= op.title %>:- <b><%=  ((op_count*100)/@vote_poll.answers.count.to_f).round(2) %>%</b><br>
<% end %>

<%#= pie_chart @vote_poll.answers.group(:vote_option_id).count %>
<%#= line_chart @vote_poll.answers.map { |goal|
    {name: goal.title}
} %>


<!-- <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          [
            <#% @vote_option.each do |op| 
              op_count = op.answers.count
              ((op_count*100)/@vote_option.count.to_f).round(2)
            end %>
          ]
        ]);

        var options = {
          title: 'My Daily Activities'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
    <div id="piechart" style="width: 900px; height: 500px;"></div> -->


<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>


 <script>
        $(function () {
            var chart;
            $(document).ready(function () {
                chart = new Highcharts.Chart({
                    chart:{
                        renderTo:'container',
                        type:'column'
                    },
                    title:{
                        text:'<%= Date.today.strftime("%B")%>'
                    },
                    xAxis:{
                        categories:[

                            '<%= Date.today.strftime("%B")%>'

                        ]
                    },
                    yAxis:{
                        min:0,
                        title:{
                            text:'Hours'
                        }
                    },
                    legend:{
                        layout:'vertical',
                        backgroundColor:'#FFFFFF',
                        align:'left',
                        verticalAlign:'top',
                        x:100,
                        y:70,
                        floating:true,
                        shadow:true
                    },
                    tooltip:{
                        formatter:function () {
                            return '' +
                                    'Percentage' + ': ' + this.y;
                        },

                        credits:{
                            text:'SomeText.co.uk',
                            hreft:'http://wwww.putyourlinkhere.co.uk'
                        }
                    },
                    plotOptions:{
                        column:{
                            pointPadding:0.4,
                            borderWidth:0
                        }
                    },


                    series:[
                        <% @vote_option.each do |option|%>
                        {
                            name:'<%= option.title%>',
                            data:[<%= ((option.answers.count*100)/@vote_poll.answers.count.to_f).round(2) %> ]
                        },
                        <% end %>
                    ]
                });
            });

        });
    </script>


<div id="container"> </div>