config/routes.rb
Rails.application.routes.draw do
 	devise_for :users
  

  root 'vooting_dashboard#index'

  get '/vooting_dashboard/:id' => 'vooting_dashboard#show', :as => 'vooting_dashboard'

  namespace :admin, module: nil  do
    root "admin#index"
    resources :users
    resources :vote_polls
  end
 	
 	resources :vote_options
 	resources :answers
 	resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote_poll.rb
class VotePoll < ApplicationRecord
	has_many :vote_options, dependent: :destroy
	has_many :answers, dependent: :destroy
	belongs_to :category

	validates :title, :description, :startdate, :enddate, presence: true
 	accepts_nested_attributes_for :vote_options, :allow_destroy => true
end

app/controllers/vote_polls_controller.rb
class VotePollsController < ApplicationController
  before_action :set_vote_poll, only: [:show, :edit, :update, :destroy]

  # GET /vote_polls
  # GET /vote_polls.json
  def index
    if params[:search].present?
      @vote_polls = VotePoll.where("lower(title) LIKE :prefix OR lower(title) LIKE :prefix", prefix: "%#{params[:search].downcase}%")
    elsif params[:category_id].present?
      @vote_polls = VotePoll.where(category_id: params[:category_id])
    else
      @vote_polls = VotePoll.all
    end  
    @category = Category.all
  end

  # GET /vote_polls/1
  # GET /vote_polls/1.json
  def show
  end

  # GET /vote_polls/new
  def new
    @vote_poll = VotePoll.new
  end

  # GET /vote_polls/1/edit
  def edit
  end

  # POST /vote_polls
  # POST /vote_polls.json
  def create
    @vote_poll = VotePoll.new(vote_poll_params)

    respond_to do |format|
      if @vote_poll.save
        format.js 
        # format.html { redirect_to @vote_poll, notice: 'Vote poll was successfully created.' }
        format.json { render :show, status: :created, location: @vote_poll }
      else
        format.html { render :new }
        format.json { render json: @vote_poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_polls/1
  # PATCH/PUT /vote_polls/1.json
  def update
    respond_to do |format|
      if @vote_poll.update(vote_poll_params)
        format.html { redirect_to define_admin_routes({resourceName: 'VotePoll', objectId: @vote_poll.id}), notice: 'PollVote was successfully updated.' }
        # format.html { redirect_to @vote_poll, notice: 'Vote poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_poll }
      else
        format.html { render :edit }
        format.json { render json: @vote_poll.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /vote_polls/1
  # DELETE /vote_polls/1.json
  def destroy
    @vote_poll.destroy
    respond_to do |format|
      format.html { redirect_to define_admin_routes({resourceName: 'VotePoll'}), notice: 'PollVote was successfully deleted.' }
      # format.html { redirect_to vote_polls_url, notice: 'Vote poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_poll
      @vote_poll = VotePoll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_poll_params
      params.require(:vote_poll).permit(:title, :description, :startdate, :enddate, :category_id, vote_options_attributes: [:id, :title, :vote_poll_id, :_destroy])
    end
end

app/helpers/vote_polls_helper.rb
module VotePollsHelper
end

app/views/vote_polls/_form.html.erb
<%= nested_form_for([:admin, @vote_poll], :remote => true) do |form| %>
  <% if vote_poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote_poll.errors.count, "error") %> prohibited this vote_poll from being saved:</h2>

      <ul>
      <% vote_poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-lg-12">
    <%= form.label :title %>
    <%= form.text_field :title, :class=>'form-control',:required=> true  %>
  </div>

  <div class="field col-lg-12">
    <%= form.label :description %>
    <%= form.text_field :description, :class=> 'form-control',:required=> true  %>
  </div>

  <div class="field col-lg-12">
    <%= form.label :startdate %>
    <%= form.text_field :startdate, :class=>'form-control datetimepicker1 ' , :id=>'start_date',  autocomplete: :off  , :required=> true %>
  </div>
    <!-- <div class="form-group">
      <div class='input-group date datetimepicker' id='start_date'>
          <input type='text' class="form-control" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
    </div> -->

   
  
  <div class="field col-lg-12">
    <%= form.label :enddate %>
    <%= form.text_field :enddate, :class=>'form-control datetimepicker1', :id=>'end_date', autocomplete: :off, :required=> true %>
  </div>

   <div class="field col-lg-12">
    <%= form.label :Category%>
    <%= form.collection_select :category_id, Category.all, :id, 
      :category_name, {:prompt=> "Select a category"}, class: 'form-control', :required=> true  %>
  </div>
  <br>
  <p class="text-center"><%= form.link_to_add "Add a Answer", :vote_options, :data => { :target => "#tasks" }, class: "btn btn-primary" %></p>
   
  <table id="tasks">
    <%= form.fields_for :vote_options do |answer_form| %>
      <div class="field col-lg-12">
          <%= answer_form.text_field :title  ,class: "form-control mynewinput1", placeholder: "Question" %><br>
          <%= answer_form.link_to_remove "Remove", class: "btn btn-danger" %>
      </div>
    <% end %>
  </table>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<!-- DateTime Picker gem script  -->
<!-- 
<script type="text/javascript">
  $(document).ready(function(){
    $('.datetimepicker1').datetimepicker({
        format: 'DD MMM YYYY LT',          // 12 Aug 2019 print date this format
        sideBySide: true,
    }).on("changeDate", function (e) {
      var start_date = $("#start_date").val(); 
      var end_date = $("#end_date").val();  // get a string format date
      if (start_date != "" && end_date != ""){
          start_date = new Date(start_date);
          end_date = new Date(end_date); // convert string date to date format 
          if (end_date < start_date){
            alert("End date should be greater or equal to start Date");
            $(this).val("");   
          }
      }
    });
  });
</script>
 -->

<!-- Start_Date & End_Date Validation  -->

<script type="text/javascript">
  $(document).ready(function(){
    $(".datetimepicker1").datepicker({
      format: 'dd M yyyy',          // 12 Aug 2019 print date this format
      autoclose: true,
      todayHighlight: true,
      orientation: 'auto top',
      todayBtn: "linked"
    }).on("changeDate", function (e) {
      var start_date = $("#start_date").val(); 
      var end_date = $("#end_date").val();  // get a string format date

      if (start_date != "" && end_date != ""){
          start_date = new Date(start_date);
          end_date = new Date(end_date); // convert string date to date format 
          if (end_date < start_date){
            alert("End date should be greater or equal to start Date");
            $(this).val("");   
          }
      }
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $(".datetimepicker1").datepicker('setStartDate', 'Date.Today');
  });
</script>

<!-- Style -->

<style type="text/css">
  .mynewinput1 {
    width:644%;
  }
</style>

app/views/vote_polls/_show_poll.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vote_poll.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vote_poll.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @vote_poll.startdate.strftime "%a, %-d %b %Y" %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @vote_poll.enddate.strftime "%a, %-d %b %Y" %>
</p>

<%= link_to 'Edit', edit_admin_vote_poll_path(@vote_poll), class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_vote_polls_path, class: 'btn btn-info' %>

app/views/vote_polls/create.js.erb
$("#from_show").html("<%= escape_javascript render 'vote_polls/show_poll' %>"); 

app/views/vote_polls/edit.html.erb
<h1 class="text-center">Editing Vote Poll</h1>

<%= render 'form', vote_poll: @vote_poll %>

<%= link_to 'Show', admin_vote_poll_path, class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_vote_polls_path,  class: 'btn btn-info', style: 'height:20%;width:10%';  %>

app/views/vote_polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Vote Polls</h1><br>

<%= form_tag "/admin/vote_polls", :method=>"get" do %>
  <div class="col-md-11">
    <%= text_field_tag :search, nil, :placeholder=>"search event", class: 'form-control' %>
   </div> 
   <div class="col-md-1"> 
    <%= submit_tag "search" , class: 'btn btn-success'%>
  </div> 
<% end %><br><br>
  
  <h1>Categories</h1>
    <%= select_tag "Select", options_from_collection_for_select( @category, "id", "category_name"), {:prompt=> "Select a category", :class=> "my_filter select_subcategory form-control"}%>

  <script type="text/javascript">
    $(function(){
      $('select.my_filter').on('change', function(){
        window.location = "/admin/vote_polls?category_id=" + $(this).val();
      })
    })
  </script><br><br>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Startdate</th>
        <th>Enddate</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vote_polls.each do |vote_poll| %>
        <tr>
          <td><%= vote_poll.title %></td>
          <td><%= vote_poll.description %></td>
          <td><%= vote_poll.startdate.strftime "%a, %-d %b %Y " %></td>
          <td><%= vote_poll.enddate.strftime "%a, %-d %b %Y " %></td>
          <td><%= link_to 'Show', admin_vote_poll_path(vote_poll), :class=> 'btn btn-info' %></td>
          <td><%= link_to 'Edit', edit_admin_vote_poll_path(vote_poll), :class=> 'btn btn-warning' %></td>
          <td><%= link_to 'Destroy',  admin_vote_poll_path(vote_poll), :class=> 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Vote Poll', new_admin_vote_poll_path, class: 'btn btn-primary' %>

app/views/vote_polls/new.html.erb
<h1 class="text-center">New Vote Poll</h1>

<div id= "from_show">
	<%= render 'form', vote_poll: @vote_poll %>
</div>


<%#= link_to 'Back', admin_vote_polls_path,  class: 'btn btn-info', style: 'height:20%;width:10%';  %>

app/views/vote_polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vote_poll.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vote_poll.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @vote_poll.startdate.strftime "%a, %-d %b %Y %I:%M %p" %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @vote_poll.enddate.strftime "%a, %-d %b %Y %I:%M %p" %>
</p>

<%= link_to 'Edit', edit_admin_vote_poll_path(@vote_poll), class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_vote_polls_path, class: 'btn btn-info' %>